{"data": "Where did Athanasius flee to after this attempt?"}